I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script call
    call chapter1
  File "game/chapter1.rpy", line 75, in script
    menu:
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script call
    call chapter1
  File "game/chapter1.rpy", line 75, in script
    menu:
  File "F:\renpy-7.3.5-sdk\renpy\ast.py", line 1631, in execute
    next_node(self.items[choice][2][0])
IndexError: list index out of range

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Orin 0.1
Mon Nov 23 22:04:58 2020
